---
jobs:
- name: job-deploy-app
  public: true
  serial: true
  plan:
  - get: resource-web-app
    trigger: true
  - put: resource-deploy-web-app

resources:
- name: resource-web-app
  type: git
  source:
    uri: https://github.com/ntdt/cf-php.git

- name: resource-deploy-web-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{cf_username}}
    password: {{cf_password}}
    organization: {{cf_organization}}
    space: {{cf_space}}
    skip_cert_check: false
